spring:
  application:
    name: yc-snacks
  datasource:
    url: jdbc:mysql://8.135.96.3:3307/db_snakes?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useCompression=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
